language: go
sudo: required
go:
  - 1.5
  - tip
env:
  - GO15VENDOREXPERIMENT=1
install:
  - wget https://github.com/Masterminds/glide/releases/download/0.9.0/glide-0.9.0-linux-amd64.tar.gz -O - | tar -xz
  - sudo mv linux-amd64/glide /usr/local/bin/ && rm -rf linux-amd64
  - glide up
script:
  - make test
